### ISSUE TITLE
I want to get Xs. Is there any code for Gs?

### ISSUE THREAD

**Issue by xulingling516** [futscdav/Chunkmogrify#11]
Weights are specified by a set of n segmentation masks S that can be specified manually or generated automatically by a segmentation network Gs using a latent code Xs.  I want to get Xs. Is there any code for Gs?  
.

**Comment by xulingling516** [comment]
![image](https://user-images.githubusercontent.com/66709839/234218363-891ab763-ef3d-4496-9e22-86a32199d538.png)

**Comment by futscdav** [comment]
It's a bit more advanced usage, but you can change `max_segments` in `_config.yaml` to something like 8 or 10 and then change the segment drawing by clicking middle mouse button. If you want to save the latent codes, you can do so via the menu. The automatic segmentation described in the full ECCV paper is not implemented in this UI version, as it's primarily aimed at interactive scenarios.
