### ISSUE TITLE
Error: Pickle data was truncated

### ISSUE THREAD

**Issue by Wythneth** [futscdav/Chunkmogrify#3]
I followed every step and everything installed correctly, but as soon as I hit "projection steps," I get the error message:

Pickle data was truncated.

Any help would be appreciated, thanks :)

**Comment by futscdav** [comment]
Hard to say what the problem could be. Can you try deleting the `.pkl` files in the `resources` folder and running again, to redownload the pickle?

**Comment by alrightalrightalrightalrightalright** [comment]
i had the same problem, ffhq.pkl in resources was only 14mb and deleting and running again fixed it, thanks.
