### ISSUE TITLE
[CUDA out of memory] - How much VRAM do we need to run this project?

### ISSUE THREAD

**Issue by illtellyoulater** [futscdav/Chunkmogrify#4]
Hello, I'm receiving "CUDA out of memory" errors just a little after pressing the Projection Steps button.

I only have 3 Gb VRAM, could this be enough? **If not, is there a way to lower the requirements?**

I've tried using the smallest JPEG at 320 * 200 px with a size of just 5 Kb, but it was still crashing...

If anything else fails, how could I run it on CPU?

**Comment by futscdav** [comment]
Hello,

You will need at least 8 gb of vram to run it comfortably (though some parts work with 6). Running it on the CPU is simple enough, but so slow that the interactive parts are not fun to use.

to do it, open `_config.yaml` in any text editor and change the `device: cuda:0` line to `device: cpu`.
