### ISSUE TITLE
"RuntimeError: "slow_conv_transpose2d_out_cpu" not implemented for 'Half'"

### ISSUE THREAD

**Issue by illtellyoulater** [futscdav/Chunkmogrify#5]
Hello, 
I'm running the software on CPU by modifying  _config.yaml as you documented in another issue.

After drawing a mask and processing some projections, I want to edit facial features and in order to do that I create a new attribute with the down-pointing arrows and then I click on "S Edit" but as soon as I do that I receive the following error message:

```
  File "...\Chunkmogrify-master\torch_utils\ops\conv2d_gradfix.py", line 43, in conv_transpose2d
    return torch.nn.functional.conv_transpose2d(input=input, weight=weight, bias=bias, stride=stride, padding=padding, output_padding=output_padding, groups=groups, dilation=dilation)
RuntimeError: "slow_conv_transpose2d_out_cpu" not implemented for 'Half'
```

**Comment by futscdav** [comment]
Fixed by forcing fp32 for running on cpu. I've tested running on cpu and didn't find any more issues after commit 16d2ce6. Let me know if you find any other problems!
