### ISSUE TITLE
"RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

### ISSUE THREAD

**Issue by illtellyoulater** [futscdav/Chunkmogrify#6]
Hello, 
I'm running the software on CPU by modifying  _config.yaml as you documented in another issue.

After drawing a mask and processing some projections, I want to edit facial features and in order to do that I create a new attribute with the down-pointing arrows and then I click on "Style Edit" but as soon as I do that I receive the following error message:

```
  File "...\Chunkmogrify-master\styleclip_mapper.py", line 13, in fused_leaky_relu
    input + bias.view(1, *rest_dim, bias.shape[0]), negative_slope=negative_slope
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by futscdav** [comment]
There was a leftover cuda transfer in the styleclip code. I've pushed a fix for it now, so if you update, it should work.
