### ISSUE TITLE
Hello, my graphics card is T4, I encountered this problem while running, Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n', is my graphics card too old? Or what about other issues?

### ISSUE THREAD

**Issue by baixinping618** [futscdav/Chunkmogrify#7]

**Comment by ucalyptus2** [comment]
u need ninja to build this

**Comment by futscdav** [comment]
Building the stylegan custom ops can fail at multiple steps, so it's not the easiest to debug remotely. The message is mostly harmless, everything should still work, albeit slightly slower than it could be.
