### ISSUE TITLE
Mac M1 processer cpp compile error (without cuda)

### ISSUE THREAD

**Issue by whatisand** [futscdav/Chunkmogrify#8]
Hello, I found a error when run app.py.

My environment is Mac M1.

Actually, I meet another error when install pytorch with CUDA version. So I install pytorch without CUDA.

``` bash
extensions/canvas_to_masks.cpp:61:31: error: expected expression
    bool output_wrong_array = [output, h, w, num_color]() {
                              ^
extensions/canvas_to_masks.cpp:73:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        auto descr = PyArray_DescrFromType(NPY_FLOAT);
        ^
extensions/canvas_to_masks.cpp:129:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    auto x = PyModule_Create(&python_module);
    ^
```

Do you know what is wrong?

**Comment by futscdav** [comment]
Interestingly your setuptools defaults to using pre C++11 standard. I've made it so it should pass the flag to compile with `--std=c++11` now, so try pulling and rerunning again. I don't have a Mac to reproduce this on, so please let me know if there are other issues.

**Comment by whatisand** [comment]
@futscdav WOW It's work! Thank you.

**Comment by whatisand** [comment]
FYI) I can build and run it now. But, it is not work when I add an image and try `projection step`.
I think this error is about another issue.
